### ISSUE TITLE
doesn't work in ammonite

### ISSUE THREAD

**Issue by jozic** [propensive/kaleidoscope#4] opened 2018-03-21 19:28 UTC
Not sure if something can be made here except renaming, but reporting anyway
 
When I tried it in ammonite repl, it failed

```scala
Welcome to the Ammonite Repl 1.0.5
(Scala 2.12.4 Java 1.8.0_161)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
> import $ivy.`com.propensive::kaleidoscope:0.1.0` 
import $ivy.$                                   

> import kaleidoscope._ 
import kaleidoscope._

> "o" match { case r"oops" =>  } 
cmd2.sc:1: type mismatch;
 found   : StringContext
 required: ?{def r: ?}
Note that implicit conversions are not applicable because they are ambiguous:
 both method RegexContextMaker in trait Extensions of type (s: StringContext)ammonite.ops.RegexContext
 and method RegexStringContext in package kaleidoscope of type (sc: StringContext)kaleidoscope.package.RegexStringContext
 are possible conversion functions from StringContext to ?{def r: ?}
val res2 = "o" match { case r"oops" =>  }
                            ^
Compilation Failed

>  
```
cc @lihaoyi

**Comment by propensive** [comment] 2018-06-15 14:58
Ah... so Ammonite is defining its own `r` interpolator.

I'm doing a bunch of refactoring right now, but I've added a duplicate of the `r` interpolator called `regex`, which shouldn't be ambiguous.

Normally I wouldn't rename something just because another library uses it, but this is Ammonite, it's difficult to work around, and `r` isn't exactly the most namespace-friendly choice.

**Closed by propensive** 2018-06-15 14:58 UTC
